version: '3.8'

services:
  db:
    image: postgres:16.1-alpine
    container_name: nti
    # restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=nti_db
    volumes:
      - ./volume:/var/lib/mysql:z
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
